/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    courses: Course;
    lessons: Lesson;
    modules: Module;
    agents: Agent;
    tools: Tool;
    'learning-records': LearningRecord;
    'user-preferences': UserPreference;
    users: User;
    media: Media;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    courses: CoursesSelect<false> | CoursesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    tools: ToolsSelect<false> | ToolsSelect<true>;
    'learning-records': LearningRecordsSelect<false> | LearningRecordsSelect<true>;
    'user-preferences': UserPreferencesSelect<false> | UserPreferencesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'chat-history': ChatHistory;
    'system-settings': SystemSetting;
  };
  globalsSelect: {
    'chat-history': ChatHistorySelect<false> | ChatHistorySelect<true>;
    'system-settings': SystemSettingsSelect<false> | SystemSettingsSelect<true>;
  };
  locale: 'en' | 'zh';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: string;
  slug: string;
  title: string;
  description?: string | null;
  coverImage?: (string | null) | Media;
  order?: number | null;
  status: 'draft' | 'published';
  /**
   * If enabled, user learning sessions for this course will be recorded unless the user opts out.
   */
  defaultTrackingEnabled: boolean;
  levels?:
    | {
        key: string;
        label: string;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Lessons belong to a course and contain multiple modules. Optional level key groups lessons within a course.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: string;
  title: string;
  slug: string;
  /**
   * Optional numeric position used to sort lessons within the course.
   */
  order?: number | null;
  summary?: string | null;
  /**
   * Course this lesson belongs to.
   */
  course: string | Course;
  /**
   * Optional level key (string) for grouping lessons within a course.
   */
  level?: string | null;
  /**
   * Modules linked to this lesson sync automatically based on each module configuration.
   */
  modules?: (string | Module)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Modules are the lowest level of lesson content. Select a module type, then provide the matching media and copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: string;
  title: string;
  slug: string;
  /**
   * Optional numeric position used to order modules within a lesson.
   */
  order?: number | null;
  lesson: string | Lesson;
  /**
   * Determines how the lesson module is rendered for learners.
   */
  type: 'audioSlideshow' | 'video' | 'richPost' | 'audio' | 'webPage';
  /**
   * Optional short summary that appears in lesson overviews.
   */
  summary?: string | null;
  /**
   * Embed a web page or external content.
   */
  webPage?: {
    /**
     * The URL to display.
     */
    url: string;
  };
  /**
   * Slides with imagery and per-slide audio clips. Works with the existing slideshow + audio player.
   */
  audioSlideshow?: {
    /**
     * Ordered slides presented alongside narration. At least one slide is required.
     */
    slides: {
      /**
       * Optional slide title displayed in the player and analytics.
       */
      title?: string | null;
      /**
       * Primary visual for the slide. Required when no video is present.
       */
      image?: (string | null) | Media;
      /**
       * Optional slide-specific audio narration.
       */
      audio?: (string | null) | Media;
      /**
       * Optional rich text copy that appears beneath the image.
       */
      body?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      id?: string | null;
    }[];
    /**
     * Optional transcript or extended notes for the module.
     */
    transcript?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Upload a video or provide an external streaming URL with supporting copy.
   */
  video?: {
    /**
     * Upload a hosted video file (MP4, MOV, etc.).
     */
    videoFile?: (string | null) | Media;
    /**
     * External streaming URL (e.g., Mux, Vimeo, S3). Use when not uploading a file.
     */
    streamUrl?: string | null;
    /**
     * Optional poster image displayed before playback.
     */
    posterImage?: (string | null) | Media;
    /**
     * Optional caption/subtitle files (WebVTT).
     */
    captions?:
      | {
          label: string;
          file: string | Media;
          /**
           * BCP-47 language tag (e.g., en, en-US, zh-CN).
           */
          language?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional transcript or supporting copy for the video.
     */
    transcript?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Long-form lesson content combining text and media blocks.
   */
  richPost?: {
    body: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Optional supporting images or documents embedded in the post.
     */
    mediaGallery?:
      | {
          media: string | Media;
          caption?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * One or more audio tracks presented without slides.
   */
  audio?: {
    tracks: {
      title: string;
      audio: string | Media;
      /**
       * Optional cover art for this track.
       */
      image?: (string | null) | Media;
      /**
       * Optional duration in seconds (used for progress estimates).
       */
      durationSeconds?: number | null;
      /**
       * Optional per-track transcript or notes.
       */
      transcript?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      id?: string | null;
    }[];
    /**
     * Optional introduction shown before the playlist.
     */
    introduction?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Optional supporting links or downloads for the module.
   */
  resources?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: string;
  title: string;
  description?: string | null;
  iconType?: ('material' | 'image') | null;
  /**
   * Material Icon name (e.g., "psychology", "chat", "school")
   */
  icon?: string | null;
  iconImage?: (string | null) | Media;
  /**
   * The API Key from Dify for this agent
   */
  difyApiKey: string;
  /**
   * The base URL for the Dify API (e.g., https://ai.babblinguide.cn/v1)
   */
  difyApiUrl?: string | null;
  /**
   * Initial message sent by the agent when chat starts
   */
  welcomeMessage?: string | null;
  /**
   * Order in the list (lower numbers first)
   */
  order?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools".
 */
export interface Tool {
  id: string;
  title: string;
  description?: string | null;
  /**
   * Must be a full URL beginning with http:// or https://
   */
  url: string;
  /**
   * Optional grouping label shown as a pill in the app (e.g., "Test", "Tool")
   */
  category?: string | null;
  /**
   * Optional Material Icon name (e.g., "science"). Leave blank to use the default icon.
   */
  icon?: string | null;
  status: 'draft' | 'published';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-records".
 */
export interface LearningRecord {
  id: string;
  user: string | User;
  source: 'auto' | 'manual';
  clientId: string;
  lessonId: string;
  lessonTitle?: string | null;
  runId?: string | null;
  startedAt: string;
  endedAt: string;
  plannedSeconds: number;
  durationSeconds?: number | null;
  speed?: number | null;
  finished?: boolean | null;
  segments?: number | null;
  /**
   * Optional learner-supplied context for manual entries.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  displayName: string;
  avatar?: (string | null) | Media;
  /**
   * Material Icon name for avatar (e.g., person, face, school). Used when no avatar image is uploaded.
   */
  avatarIcon?: string | null;
  /**
   * A short biography (max 500 characters)
   */
  bio?: string | null;
  /**
   * City, country, or region
   */
  location?: string | null;
  /**
   * Personal website or social media profile URL
   */
  website?: string | null;
  /**
   * Used for age-appropriate content and analytics
   */
  dateOfBirth?: string | null;
  /**
   * User's native language
   */
  nativeLanguage?: string | null;
  /**
   * Languages the user is currently learning
   */
  learningLanguages?:
    | {
        language: string;
        level?: ('beginner' | 'elementary' | 'intermediate' | 'advanced' | 'native') | null;
        id?: string | null;
      }[]
    | null;
  role: 'user' | 'editor' | 'manager';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-preferences".
 */
export interface UserPreference {
  id: string;
  user: string | User;
  global?: {
    playbackSpeed?: number | null;
    sessionDuration?: number | null;
  };
  courseOverrides?:
    | {
        course: string | Course;
        trackingEnabled: boolean;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'courses';
        value: string | Course;
      } | null)
    | ({
        relationTo: 'lessons';
        value: string | Lesson;
      } | null)
    | ({
        relationTo: 'modules';
        value: string | Module;
      } | null)
    | ({
        relationTo: 'agents';
        value: string | Agent;
      } | null)
    | ({
        relationTo: 'tools';
        value: string | Tool;
      } | null)
    | ({
        relationTo: 'learning-records';
        value: string | LearningRecord;
      } | null)
    | ({
        relationTo: 'user-preferences';
        value: string | UserPreference;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  coverImage?: T;
  order?: T;
  status?: T;
  defaultTrackingEnabled?: T;
  levels?:
    | T
    | {
        key?: T;
        label?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  summary?: T;
  course?: T;
  level?: T;
  modules?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  lesson?: T;
  type?: T;
  summary?: T;
  webPage?:
    | T
    | {
        url?: T;
      };
  audioSlideshow?:
    | T
    | {
        slides?:
          | T
          | {
              title?: T;
              image?: T;
              audio?: T;
              body?: T;
              id?: T;
            };
        transcript?: T;
      };
  video?:
    | T
    | {
        videoFile?: T;
        streamUrl?: T;
        posterImage?: T;
        captions?:
          | T
          | {
              label?: T;
              file?: T;
              language?: T;
              id?: T;
            };
        transcript?: T;
      };
  richPost?:
    | T
    | {
        body?: T;
        mediaGallery?:
          | T
          | {
              media?: T;
              caption?: T;
              id?: T;
            };
      };
  audio?:
    | T
    | {
        tracks?:
          | T
          | {
              title?: T;
              audio?: T;
              image?: T;
              durationSeconds?: T;
              transcript?: T;
              id?: T;
            };
        introduction?: T;
      };
  resources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  iconType?: T;
  icon?: T;
  iconImage?: T;
  difyApiKey?: T;
  difyApiUrl?: T;
  welcomeMessage?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools_select".
 */
export interface ToolsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  url?: T;
  category?: T;
  icon?: T;
  status?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-records_select".
 */
export interface LearningRecordsSelect<T extends boolean = true> {
  user?: T;
  source?: T;
  clientId?: T;
  lessonId?: T;
  lessonTitle?: T;
  runId?: T;
  startedAt?: T;
  endedAt?: T;
  plannedSeconds?: T;
  durationSeconds?: T;
  speed?: T;
  finished?: T;
  segments?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-preferences_select".
 */
export interface UserPreferencesSelect<T extends boolean = true> {
  user?: T;
  global?:
    | T
    | {
        playbackSpeed?: T;
        sessionDuration?: T;
      };
  courseOverrides?:
    | T
    | {
        course?: T;
        trackingEnabled?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  avatar?: T;
  avatarIcon?: T;
  bio?: T;
  location?: T;
  website?: T;
  dateOfBirth?: T;
  nativeLanguage?: T;
  learningLanguages?:
    | T
    | {
        language?: T;
        level?: T;
        id?: T;
      };
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-history".
 */
export interface ChatHistory {
  id: string;
  placeholder?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-settings".
 */
export interface SystemSetting {
  id: string;
  /**
   * The API Key for the Dify Agent used to summarize conversations.
   */
  summarizerAgentApiKey: string;
  /**
   * The base URL for the Summarizer Agent API.
   */
  summarizerAgentApiUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-history_select".
 */
export interface ChatHistorySelect<T extends boolean = true> {
  placeholder?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-settings_select".
 */
export interface SystemSettingsSelect<T extends boolean = true> {
  summarizerAgentApiKey?: T;
  summarizerAgentApiUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}